//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by evolve.rc
//
#define IDR_RIGHTCLICK_POPUP            1
#define IDC_SP_HELP                     2
#define IDC_WP_HELP                     3
#define IDC_WP_DISABLE_ALL              4
#define IDC_WP_REMOVE                   5
#define IDC_WP_INSTRUCTIONS             6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_evolveTYPE                  129
#define IDB_LOGO                        131
#define IDD_UNIVERSE                    132
#define IDD_SIMULATION_OPTIONS          134
#define IDD_NEW_UNIVERSE                135
#define IDD_KFORTH                      136
#define IDD_KFORTH_INSTRUCTION          137
#define IDD_EVOLVE_OPTIONS              138
#define IDD_VIEW_ORGANISM               139
#define IDD_WATCHPOINTS                 140
#define IDD_STRAIN_POPULATION           142
#define IDD_FIND                        143
#define IDD_MUTATION_TESTER             145
#define IDD_CELL_VISION                 146
#define IDD_ENERGY_TWEAKER              149
#define IDC_U_FILENAME                  1006
#define IDC_U_STEPS                     1007
#define IDC_U_ORGANISMS                 1008
#define IDC_U_CELLS                     1009
#define IDC_U_ORGANIC                   1010
#define IDC_U_SPORES                    1011
#define IDC_U_NBORN                     1012
#define IDC_U_NDIE                      1013
#define IDC_U_HEIGHT                    1014
#define IDC_U_WIDTH                     1015
#define IDC_U_INSTRUCTIONS              1016
#define IDC_U_CSTACK                    1017
#define IDC_U_STACK                     1018
#define IDC_U_DSTACK                    1019
#define IDC_U_GMEM                      1020
#define IDC_U_CSMEM                     1021
#define IDC_U_DSMEM                     1022
#define IDC_U_PMEM                      1023
#define IDC_U_OMEM                      1024
#define IDC_U_SMEM                      1025
#define IDC_U_TMEM                      1026
#define IDC_U_ENERGY                    1027
#define IDC_U_SEED                      1028
#define IDC_U_NSEXUAL                   1029
#define IDC_U_SPORE_ENERGY              1030
#define IDC_U_DSTACK3                   1031
#define IDC_U_ORGANIC_ENERGY            1031
#define IDC_KI_SOURCE                   1041
#define IDC_KI_INSTRUCTIONS             1042
#define IDC_KI_DATA_STACK               1043
#define IDC_KI_RUN                      1045
#define IDC_KI_COMPILE                  1046
#define IDC_KI_STEP                     1047
#define IDC_KI_LOAD                     1048
#define IDC_KI_SAVE                     1049
#define IDC_KI_RESET                    1050
#define IDC_KI_CALL_STACK               1051
#define IDC_KI_INSERT                   1052
#define IDC_KI_HELP                     1053
#define IDC_KI_R0                       1054
#define IDC_KI_R1                       1055
#define IDC_KI_R2                       1056
#define IDC_KI_R3                       1057
#define IDC_KI_R4                       1058
#define IDC_KI_R5                       1059
#define IDC_KI_R6                       1060
#define IDC_KI_R7                       1061
#define IDC_KI_R8                       1062
#define IDC_KI_R9                       1063
#define IDC_KI_PC                       1064
#define IDC_KI_CB                       1065
#define IDC_KI_ERROR                    1066
#define IDC_IKI_LIST                    1067
#define IDC_VO_MOOD                     1067
#define IDC_KI_STEP_OVER                1067
#define IDC_IKI_DESC                    1068
#define IDC_VO_ID                       1068
#define IDC_KI_BREAKPOINT               1068
#define IDC_NU_WIDTH                    1069
#define IDC_VO_R5                       1069
#define IDC_KI_WATCHPOINT               1069
#define IDC_NU_SEED                     1070
#define IDC_VO_PARENT2                  1070
#define IDC_NU_HEIGHT                   1071
#define IDC_VO_GENERATION               1071
#define IDC_NU_PROGRAM                  1072
#define IDC_VO_AGE                      1072
#define IDC_NU_BROWSE                   1073
#define IDC_VO_NCELLS                   1073
#define IDC_VO_NUM_CELLS                1073
#define IDC_NU_ENERGY                   1074
#define IDC_VO_ENERGY                   1074
#define IDC_NU_BARRIER                  1075
#define IDC_VO_MESSAGE                  1075
#define IDC_NU_HELP                     1076
#define IDC_SO_HELP                     1076
#define IDC_VO_LOCATION                 1076
#define IDC_U_HELP                      1077
#define IDC_VO_CELLIDX                  1077
#define IDC_NU_PROGRAM2                 1077
#define IDC_EO_HELP                     1078
#define IDC_VO_STRAIN                   1078
#define IDC_NU_BROWSE2                  1078
#define IDC_EO_ENABLE                   1079
#define IDC_NU_ENERGY2                  1079
#define IDC_VO_NUM_LCHILD               1079
#define IDC_NU_PROGRAM3                 1080
#define IDC_VO_STRAIN2                  1080
#define IDC_VO_XYTYPE                   1080
#define IDC_NU_ERROR                    1081
#define IDC_EO_MAP_UPDATE               1082
#define IDC_VO_PARENT1                  1082
#define IDC_NU_BROWSE3                  1082
#define IDC_EO_CHECKPOINT_INTERVAL      1083
#define IDC_VO_INSTRUCTIONS             1083
#define IDC_NU_ENERGY3                  1083
#define IDC_EO_FILENAME                 1084
#define IDC_VO_CB                       1084
#define IDC_NU_PROGRAM4                 1084
#define IDC_EO_BROWSE                   1085
#define IDC_VO_PC                       1085
#define IDC_NU_BROWSE4                  1085
#define IDC_EO_DEFAULTS                 1086
#define IDC_VO_R0                       1086
#define IDC_NU_ENERGY4                  1086
#define IDC_VO_R1                       1087
#define IDC_EO_MACROS                   1087
#define IDC_NU_PROGRAM5                 1087
#define IDC_VO_R2                       1088
#define IDC_NU_BROWSE5                  1088
#define IDC_VO_R3                       1089
#define IDC_NU_ENERGY5                  1089
#define IDC_VO_R4                       1090
#define IDC_NU_PROGRAM6                 1090
#define IDC_VO_R6                       1091
#define IDC_NU_BROWSE6                  1091
#define IDC_VO_R7                       1092
#define IDC_NU_ENERGY6                  1092
#define IDC_VO_R8                       1093
#define IDC_NU_PROGRAM7                 1093
#define IDC_VO_R9                       1094
#define IDC_NU_BROWSE7                  1094
#define IDC_VO_DATA_STACK               1095
#define IDC_NU_ENERGY7                  1095
#define IDC_VO_CALL_STACK               1096
#define IDC_NU_PROGRAM8                 1096
#define IDC_VO_HELP                     1097
#define IDC_NU_BROWSE8                  1097
#define IDC_VO_BREAKPOINT               1098
#define IDC_NU_ENERGY8                  1098
#define IDC_VO_STEP_OVER                1099
#define IDC_NU_MUTATION_SETTINGS        1099
#define IDC_SO_DUPLICATE                1100
#define IDC_VO_SIMULATE                 1100
#define IDC_SO_DELETE                   1101
#define IDC_VO_INSERT                   1101
#define IDC_SO_INSERT                   1102
#define IDC_VO_WATCHPOINT               1102
#define IDC_SO_TRANSPOSITION            1103
#define IDC_AB_HELP                     1103
#define IDC_VO_RUN                      1103
#define IDC_SO_MODIFICATION             1104
#define IDC_VO_VISION                   1104
#define IDC_SO_MUTATE_CB                1105
#define IDC_WP_CHECK2                   1105
#define IDC_WP_STEP_LIMIT               1106
#define IDC_SO_MAX_CB                   1106
#define IDC_WP_CHECK1                   1107
#define IDC_SO_MAX_CB2                  1107
#define IDC_SO_MAX_APPLY                1107
#define IDC_WP_ERROR                    1108
#define IDC_WP_LIST                     1109
#define IDC_NU_STRAIN                   1110
#define IDC_WP_CHECK3                   1111
#define IDC_NU_STRAIN2                  1111
#define IDC_WP_EXPR3                    1112
#define IDC_NU_STRAIN3                  1112
#define IDC_WP_CHECK4                   1113
#define IDC_NU_STRAIN4                  1113
#define IDC_WP_EXPR4                    1114
#define IDC_NU_STRAIN5                  1114
#define IDC_WP_CHECK5                   1115
#define IDC_NU_STRAIN6                  1115
#define IDC_WP_EXPR5                    1116
#define IDC_NU_STRAIN7                  1116
#define IDC_NU_STRAIN8                  1117
#define IDC_SP_LABEL1                   1118
#define IDC_SP_EDIT1                    1119
#define IDC_SP_LABEL2                   1120
#define IDC_FO_HELP                     1120
#define IDC_SP_EDIT2                    1121
#define IDC_FO_QUERY                    1121
#define IDC_SP_LABEL3                   1122
#define IDC_FO_FIND                     1122
#define IDC_SP_EDIT3                    1123
#define IDC_FO_COMPUTE                  1123
#define IDC_SP_LABEL4                   1124
#define IDC_FO_INSTRUCTIONS             1124
#define IDC_WP_EXPR2                    1125
#define IDC_SP_EDIT4                    1125
#define IDC_WP_EXPR1                    1126
#define IDC_SP_LABEL5                   1126
#define IDC_FO_RESULTS                  1126
#define IDC_SP_EDIT5                    1127
#define IDC_FO_ERROR                    1127
#define IDC_SP_LABEL6                   1128
#define IDC_MT_GOAL                     1128
#define IDC_SP_EDIT6                    1129
#define IDC_MT_START                    1129
#define IDC_SP_LABEL7                   1130
#define IDC_MT_LOAD1                    1130
#define IDC_SP_EDIT7                    1131
#define IDC_MT_LOAD2                    1131
#define IDC_SP_LABEL8                   1132
#define IDC_MT_SAVE1                    1132
#define IDC_SP_EDIT8                    1133
#define IDC_MT_HELP                     1133
#define IDC_MT_RUN                      1134
#define IDC_MT_STEP                     1135
#define IDC_MT_RESET                    1136
#define IDC_MT_SCORE                    1137
#define IDC_MT_BRED                     1138
#define IDC_MT_GENERATION               1139
#define IDC_MT_LITTER                   1140
#define IDC_MT_DEL                      1141
#define IDC_AB_INFO                     1141
#define IDC_MT_DUP                      1142
#define IDC_CV_HELP                     1142
#define IDC_MT_INS                      1143
#define IDC_CV_NW_WHERE                 1143
#define IDC_MT_SEED                     1144
#define IDC_CV_NW_WHAT                  1144
#define IDC_MT_MOD                      1145
#define IDC_CV_N_WHERE                  1145
#define IDC_MT_TRANS                    1146
#define IDC_CV_NE_WHERE                 1146
#define IDC_MT_MCB                      1147
#define IDC_CV_E_WHERE                  1147
#define IDC_MT_SAVE2                    1148
#define IDC_CV_SE_WHERE                 1148
#define IDC_CV_S_WHERE                  1149
#define IDC_CV_SW_WHERE                 1150
#define IDC_CV_W_WHERE                  1151
#define IDC_CV_N_WHAT                   1152
#define IDC_CV_NE_WHAT                  1153
#define IDC_CV_E_WHAT                   1154
#define IDC_CV_SE_WHAT                  1155
#define IDC_CV_S_WHAT                   1156
#define IDC_CV_SW_WHAT                  1157
#define IDC_CV_W_WHAT                   1158
#define IDC_CV_CELL                     1159
#define IDC_ET_ENERGY                   1161
#define IDC_SP_STATIC1                  1163
#define IDC_SP_STATIC2                  1164
#define IDC_FO_EDIT                     1164
#define IDC_SP_STATIC3                  1165
#define IDC_SP_STATIC4                  1166
#define IDC_SP_STATIC5                  1167
#define IDC_SP_STATIC6                  1168
#define IDC_SP_STATIC7                  1169
#define IDC_SP_STATIC8                  1170
#define ID_VIEW_UNIVERSE                32774
#define ID_VIEW_ORGANISM                32775
#define ID_SIMULATION_CONTINUE          32782
#define ID_HELP_CONTENTS                32791
#define ID_TB_SIMULATE                  32805
#define ID_TB_STOP                      32806
#define ID_TB_ZOOM_IN                   32807
#define ID_TB_ZOOM_OUT                  32808
#define ID_TB_VIEW_ALL                  32809
#define ID_TB_EXAMINE                   32810
#define ID_TB_CONTINUE                  32811
#define ID_TB_STEP                      32812
#define ID_VIEW_ZOOM_IN                 32817
#define ID_VIEW_ZOOM_OUT                32818
#define ID_VIEW_VIEW_ALL                32819
#define ID_EDIT_SIM_PROPERTIES          32820
#define ID_TOOLS_KFORTH_INTERPRETER     32822
#define ID_SIMULATION_SINGLE_STEP       32834
#define ID_SIMULATION_START             32835
#define ID_SIMULATION_STOP              32836
#define ID_EDIT_DELETE                  32837
#define ID_TOOLS_OPTIONS                32850
#define ID_Menu                         32852
#define ID_EDIT_LOCK_SIMULATION         32854
#define ID_VIEW_STRAIN_POPULATION       32858
#define ID_HELP_KFORTH                  32863
#define ID_HELP_ORGANISMS               32864
#define ID_Menu32867                    32867
#define ID_TOOLS_OPENGL_DIALOG          32870
#define ID_VIEW_3D                      32871
#define ID_EDIT_RIGHTCLICK              32875
#define ID_EDIT_RIGHTCLICK_NOTHING      32879
#define ID_EDIT_RIGHTCLICK_BARRIER      32880
#define ID_EDIT_RIGHTCLICK_DYE          32881
#define ID_EDIT_RIGHTCLICK_MOVE         32883
#define ID_EDIT_RIGHTCLICK_THIN_BARRIER 32885
#define ID_EDIT_CLEAR_DYE               32887
#define ID_EDIT_RIGHTCLICK_CHOOSER      32889
#define ID_OFF_SETENERGY                32894
#define ID_EDIT_RIGHTCLICK_ENERGY       32903

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
